# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 03:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('event_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('creator_id', models.CharField(default='Admin', max_length=40)),
                ('event_level', models.CharField(default='General', max_length=10)),
                ('event_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('end_time', models.CharField(default='', max_length=50)),
                ('all_day', models.BooleanField()),
                ('description', models.TextField(default='')),
                ('updated', models.DateTimeField(default=datetime.datetime(2017, 9, 10, 8, 48, 55, 547303, tzinfo=utc))),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
