# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(default='Admin', max_length=40)),
                ('event_level', models.CharField(default='General', max_length=10)),
                ('event_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
