# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 05:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_auto_20170910_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender',
            name='all_day',
        ),
        migrations.RemoveField(
            model_name='calender',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='calender',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 10, 10, 40, 57, 270617, tzinfo=utc)),
        ),
    ]
