# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_auto_20170910_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 10, 11, 57, 5, 837635, tzinfo=utc)),
        ),
    ]
