# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0007_auto_20170910_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
