# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0009_auto_20170910_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender',
            name='updated',
        ),
    ]
